name = "simple-blog"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "simple-blog"

[env.preview]
name = "simple-blog-preview"

# Build configuration for Cloudflare Pages
[build]
command = "npm run build"
cwd = "."

# Pages configuration
[[pages_builds]]
build_command = "npm run build"
build_output_directory = ".next"
